# Generated by Django 3.0.7 on 2020-08-05 02:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RUserdata",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=20, null=True)),
                ("Email", models.EmailField(max_length=40)),
                ("Phone_no", models.IntegerField()),
                ("Role", models.CharField(max_length=15)),
                ("Branch", models.CharField(max_length=30)),
                ("Clg_Year", models.CharField(default=None, max_length=10)),
                ("Password", models.CharField(max_length=10)),
                ("CmfPassword", models.CharField(max_length=10)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
