# Generated by Django 3.0.7 on 2020-08-05 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruserdata",
            name="Name",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
