# Generated by Django 3.0.7 on 2020-08-07 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Notes", "0002_auto_20200805_0900"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.CharField(max_length=15, null=True)),
                ("Branch", models.CharField(max_length=30, null=True)),
                ("Subject", models.CharField(max_length=30, null=True)),
                ("Type", models.CharField(max_length=15, null=True)),
                ("Uploadfile", models.FileField(null=True, upload_to="")),
                ("Desc", models.CharField(max_length=150, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
